import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import SessionWrapper from "./SessionWrapper";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        {/* <head>
        <script src="https://accounts.google.com/gsi/client" async defer></script>
      </head> */}
        <Toaster />
        <body className={inter.className}>
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
